HW1: Урок 1. Асинхронное программирование
AnniWeb/Q2Web pull request #1
Opened 2021-06-19 17:43 UTC by AnniWeb

2021-06-24 13:42 UTC, vladimir-shmidt requested changes

2021-06-24 13:42 UTC, vladimir-shmidt commented on L1Proxy/Model/Post.cs
> +            bool result = UserId > 0 && Id > 0 && Title.Length > 0;
для  new Post().Valid() произойдет исключение так как Title.Length может взяться от null -> null.Length

2021-06-24 13:42 UTC, vladimir-shmidt commented on L1Proxy/Program.cs
> +                    await Task.Delay(1000);
хорошая идея с повторнеием например когда сеть нестабильная и чтото отвалилось посередине
единственное не хвататет условия выхода и цикла если например сеть так и не заработает в конце концов

2021-06-24 13:42 UTC, vladimir-shmidt commented on L1Proxy/Program.cs
> +                    var post = task.Result;
что будет если в задаче на скачивание произойдет ошибка?

2021-06-24 13:43 UTC, vladimir-shmidt requested changes
хорошая аккуратная работа
общий смысл уловила
нужно сделать несколько правок

2021-06-24 14:14 UTC, AnniWeb commented on L1Proxy/Program.cs
> +                    await Task.Delay(1000);
добавила проверку токенадобавила проверку токена для прерывания для прерывания

2021-06-24 14:16 UTC, AnniWeb commented on L1Proxy/Program.cs
> +                    var post = task.Result;
решила сделать проще, добавила прерывание, если хоть один пост не валиден

2021-06-24 14:17 UTC, AnniWeb commented on L1Proxy/Model/Post.cs
> +            bool result = UserId > 0 && Id > 0 && Title.Length > 0;
rider посоветовал заменить на !string.IsNullOrEmpty(Title)

2021-07-05 14:10 UTC, vladimir-shmidt requested changes

2021-07-05 14:10 UTC, vladimir-shmidt commented on L1Proxy/Program.cs
> +                    var post = task.Result;
валидность поста не решает проблему. Дело в самом таске. Если в нем проихойдет ошибка то вызов поля  Result приведет к выбросу исключения которое приведет к отсановке приложения или завершению обработки результатов скачивания

2021-07-05 14:26 UTC, vladimir-shmidt approved these changes
задание ок

2021-07-11 12:28 UTC, closed without merging